### ISSUE TITLE
Don't touch simple_app unless I'm done with it

### ISSUE THREAD

**Issue by nasaWelder** [needmoney90/merkato#109]
I don't go into your garage and reorganize your toolbox in the middle of a project

**Comment by nasaWelder** [comment]
I used to be able to actually see more than 5 lines of code while working on it.
![screenshot at 2018-05-22 00 00 54](https://user-images.githubusercontent.com/33912627/40344717-543e7026-5d53-11e8-8a2f-c931ffcb80f5.png)

**Comment by nasaWelder** [comment]
None of those params are close to being final. If I wanna change rows and columns, or pads around I need to be able to see all of them to at once so I know how tweaking one affects the others. The way I had it all the params were visually in a table so I could go down the line tweaking them all at once. Just no

**Comment by needmoney90** [comment]
Our attempt was to set it up such that we could understand what everything did, and (hopefully) build out a pane for visually displaying the orderbook. In it's existing form, it was difficult to parse for us, and understand the parameters you were passing in so that we could actually work on things ourselves. 

We've completed the majority of the necessary commands in the backend, and are attempting to hook things up to the front end - what do you suggest we do? If you want me to revert the spacing on those commands to single lines, I can do so.

**Comment by needmoney90** [comment]
I'm sorry to have stepped into your GUI work so suddenly, but this is literally the thing that's left to do, everything else is polish and not needed for a working alpha

**Comment by nasaWelder** [comment]
I can do the order book tonight. I had wanted to see someone run a merkato with cli then copy the interface to it. Has anyone tested test exchange with merkato either?

**Comment by nasaWelder** [comment]
@livinginformation what function returns order book data, what format?

**Comment by nasaWelder** [comment]
@livinginformation @15chrjef sorry, I'm an ass.
